Metaswitch/clearwater-cassandra

- debian/control
I changed clearwater-cassandra's dependency on cassandra to a Pre-Depends to fix the race.
> [Reviewer: Andy] Fix https://github.com/Metaswitch/clearwater-cassandra/issues/17

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Cassandra changes (following template of Metaswitch/chronos#107)
Fixes #8 and #19
> [Reviewer: Matt] Add in poll-tcp script

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Chang as discussed. Linked with https://github.com/Metaswitch/clearwater-monit/issues/15.
> Reviewer EM: Remove the troublesome poll_cassandra (for now)

- clearwater-cassandra/usr/share/clearwater/bin/restore_backup.sh
- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
- debian/control
> [Reviewer: Rob] Use 2.0.14

- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra
Add in a namespace_prefix to the start-stop-daemon call
Fixes #37
> [Reviewer: Andy] Add in a namespace_prefix

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
> [Reviewer: Rob] Add signaling namespace plumbing

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra_ring.sh
Use new namespace script in poll_cassandra_ring
Fixes #47
> [Reviewer: Rob] Use new namespace script

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Set read request timeout in yaml file. Part of the fix in https://github.com/Metaswitch/homestead/pull/271
> [Reviewer: Alex] Add read request timeout

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_failed_plugin.py
Cassandra failed plugin for https://github.com/Metaswitch/clearwater-etcd/pull/208
> [Reviewer: Alex] Add cass failed plugin

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Part of https://github.com/Metaswitch/clearwater-etcd/pull/223
> [No reviewer] Write files atomically, avoid corruption

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Hi Ellie, please can you review this PR to allow cassandra to start on IPv6 only systems. There are two changes:
* Tell the JVM to not prefer IPv4 addresses. 
* Have cassandra bind the RPC socket to ::1 instead of 127.0.0.1. 
This isn't enough to get cassandra completely working on IPv6, but it's a step in the right direction. 
I've tested that:
* On an IPv4 system cassandra comes up and you can connect to it by running `cqlsh` in the signlaing namespace. 
* On an IPv6 systrem cassandra comes up and you can connect using `cqlsh ::1` (the extra address is a workaround to a problem I haven't decided how to solve yet)
> [Reviewer: Ellie] Cassandra IPv6 fixes

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/failed_plugins/cassandra_failed_plugin.py
The nodetool commands need to run in the signaling namespace on split
network systems.
This should solve the problems in issue #69 .
Alex, please let me know if you can no longer review.
> [Reviewer Alex] Use signaling namespace to remove nodes from Cassandra datastore.

- debian/clearwater-cassandra.postinst
- debian/clearwater-cassandra.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Adam, it looks like I missed this change with the rest of the alarms work. Can you please take a look?
> [Reviewer Adam] Update cassandra plugin to use new alarm infrastructure.

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
See clearwater-infrastructure for the new script which this uses.
> [Reviewer Adam] Update cassandra to use new uptime infrastructure.

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Similar to https://github.com/Metaswitch/chronos/pull/236
The logging on this may be too spammy now.
> [No Reviewer] Set alarm at all stages in clustering process

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
@rkd-msw - this just pulls your changes in #88 into dev (I need these for the testing I'm doing, and I wanted to get the change to stabilise cassandra clustering into the release).
I've taken your changes directly (AMC had suggested some markups in the PR but I've not made them)
> [No reviewer] Pull fix into dev

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Basically as suggested in #87.
> [Reviewer: Ellie] Fixes for https://github.com/Metaswitch/clearwater-cassandra/issues/87

- clearwater-cassandra/usr/share/clearwater/bin/restore_backup.sh
This fixes restoring a cassandra backup. The restore method used to just copy the db files across - this doesn't work as Cassandra doesn't recognise the UUIDs. Instead, you need to preserve the existing UUIDs.
Tested live by adding a subscriber on one deployment, taking a backup, then restoring it on a different deployment, and checking that the subscriber exists on that deployment (using display_user).
> [Reviewer: Seb] Fix backup restore

- clearwater-cassandra/usr/share/clearwater/cassandra/cassandra-env.sh.template
Very speculative fix to improve 99.9% latencies - not tested.
> [No reviewer] Hopeful fix to improve 99.9 latency

- clearwater-cassandra/usr/share/clearwater/bin/remove_site_from_cassandra
- clearwater-cassandra/usr/share/clearwater/bin/update_cassandra_strategy
- debian/clearwater-cassandra.links
This PR checks in the cassandra scripts to update cassandra's replication strategy (used when moving from a non-GR deployment to a GR deployment), and a script to remove a failed site from cassandra.
> [Reviewer: Sathiyan] Check in cassandra scripts for GR

- debian/clearwater-cassandra.links
I noticed when looking at the docs that these scripts didn't have the shortcut links. This PR adds them.
> [Reviewer: Sathiyan] Create clearwater-cassandra.links

- debian/clearwater-cassandra.links
This changes the ordering of sbin and bin links
> Reorders links and puts gap between sbin and bin links
