Metaswitch/clearwater-cassandra

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
As promised, the follow on to https://github.com/Metaswitch/clearwater-infrastructure/pull/149.
Fixes https://github.com/Metaswitch/clearwater-cassandra/issues/22.
Tested on an AIO node.
> Reviewer AMC: Poll cassandra at cassandra_hostname rather than local_ip

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
Fixes https://github.com/Metaswitch/clearwater-cassandra/issues/30. If we start up Cassandra without cassandra_hostname specified in etc/clearwater/config, poll_cassandra will poll local_ip but cassandra will listen on localhost. Not any more!
> Reviewer EM: Poll 9160 on 127.0.0.1 if cassandra_hostname isn't specified

- debian/clearwater-cassandra.postinst
I've upgraded a node from Cassandra 1.2 to 2.0, and confirmed that it comes up without further manual tweaks.
> [Reviewer: Ellie] Use Java 7 when Cassandra 2.0.14 is installed

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Running `poll_cassandra_ring` repeatedly causes memory usage in Cassandra to steadily climb until it starts to cause performance issues, culminating in a STW GC.
> Reviewer Ellie - Disable poll_cassandra_ring

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Matt, can you review this change to only poll cassandra if the cassandra process has been up for 2 minutes. I've made the change in the poll_cassandra script rather than monit, as I think monit will need substantial changes to use uptime/start delay in a check program context. 
Tested live
> [Reviewer: Matt] Only poll cassandra after it's been up for 2 mins

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
Ellie, this change restarts the thrift interface if poll_cassandra fails (as discussed).  I've tested this on the dogfood system, by running `nodetool disablethrift` and checking that it is re-enabled within 10 seconds.
I've not enabled the `poll_cassandra` monitor since that's blocked on your changes to add a post-start grace period.
> Reviewer Ellie - Re-enable thrift if poll_cassandra fails

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Graeme, can you review this change to correctly call poll_cassandra when checking if the cassandra cluster is up?
Part of the fix for #54
> [Reviewer: Graeme] Check that cassandra is running correctly

- clearwater-cassandra/usr/share/clearwater/bin/do_backup.sh
- clearwater-cassandra/usr/share/clearwater/bin/restore_backup.sh
Ellie, please could you take a look at this? It is just a change to suppress some "xss = " output, which comes direct from the cassandra command line tools and to update some output from the restore script to say "restore" rather than "backup". I found evidence elsewhere of just grepping out the "xss =" line printing out Java options - see Metaswitch/clearwater-etcd#106.
> [Reviewer: Ellie] Minor changes to cassandra backup/restore scripts

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
As we discussed, this clears the NOT_YET_CLUSTERED alarm on becoming stable (which happens in two places, after initial join and after restart of a joined node), mirroring the behavior in the memcached/chronos plugins.
Fixes #61.
> Reviewer Rob - Clear alarm on stable not on joining

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
- debian/clearwater-cassandra.postinst
This changes the Cassandra clustering plugin, so that if it's in stable state and /etc/clearwater/force_cassandra_yaml_refresh exists, it will regenerate cassandra.yaml and restart Cassandra (but not delete all the data). This'll be useful if a new clearwater-cassandra version has changed the template, for example.
I've tested by upgrading a Homer node and verifying that cassandra.yaml was put into place.
Commit-by-commit review might be sensible - the first commit is a minimal rework to do this, but that meant factoring out a `write_new_cassandra_config` method with a silly number of parameters, so I've then refactored it to make that a member function.
> [Reviewer: Alex] Force cassandra.yaml refresh

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
Use check-uptime to clear alarms and avoid suprious monit failures.
> [Reviewer: None] Use updated check-uptime script.

- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/check-cassandra-uptime
Monit can't pass arguments to check-program scripts in its current version.
> [Reviewer: None] Cope with Monit restrictions

- clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh
We may wish to have a replication factor that isn't 2. This change allows that.
Tested by calling this script from another bash script like below and inspecting the output.
```
. clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh
echo $replication_str
replication_factor=3
. clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh
echo $replication_str
```
> Reviewer RKD: Allow configurable replication factor

- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
Fixes https://github.com/Metaswitch/clearwater-cassandra/issues/96. I'll live-test under Chef (initial creation of one node and scale-up to two), and Docker (verifying it basically works).
@mirw - this is the fix we discussed coming out of https://github.com/Metaswitch/clearwater-docker/pull/19
> [Reviewer: Ellie] Allow Cassandra clustering in environments without Monit (e.g. Docker)

- clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh
Rob,
Please can you review this fix to https://github.com/Metaswitch/clearwater-heat/issues/28?  Note that this also fixes #95, since I was in the area.
Tested live.  Note that clearwater-heat still takes a little while (5-6 minutes) to spin up due to monit and etcd taking some time to pull themselves together - I'm not sure whether we want to track that separately - thoughts?
Matt
> [Reviewer: Rob] Don't try to use cassandra until clearwater-cassandra is installed

- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra
Replace an old reference to the script "is_address_ipv6.py" with a reference to the new job "is-address-ipv6".
I hit this after installing http://vm-images.cw-ngv.com/cw-aio.ova (image dated 6/29/2016, 4:30:52 PM) on VirtualBox.  This was preventing Cassandra from starting, which had knock-on effects that prevented other components from starting or working correctly (e.g. I couldn't provision through Ellis).
I manually patched this one file on my cw-aio VM, and this allowed Cassandra (and everything else) to start normally.  I have not done any other testing (e.g. UTs, etc.).
> [Reviewer: MIRW] Fix up Cassandra script to use new is-address-ipv6 job

- clearwater-cassandra/usr/share/clearwater/cassandra/cassandra.yaml.template
- clearwater-cassandra/usr/share/clearwater/clearwater-cluster-manager/plugins/cassandra_plugin.py
We'd like Cassandra to listen on all addresses so that it can be used remotely.
I've left the code to listen differently if it think it's running on an IPv6 network versus an IPv4 network, but I *think* that this might be unnecessary. I've tested that this works on an IPv4 deployment spun up in Amazon, but I haven't checked that it works on a IPv6 network.
> [Reviewer: AJH] Alter Cassandra configuration to listen everywhere

- clearwater-cassandra/usr/share/clearwater/cassandra/cassandra-env.sh.template
- clearwater-cassandra/usr/share/clearwater/cassandra/cassandra.yaml.template
- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra
Merging https://github.com/Metaswitch/clearwater-infrastructure/pull/369 exposed an interesting new IPv6-ish bug, which caused the Homer staging node to start failing.
We had `cassandra_hostname=localhost` set in shared_config. This meant that after https://github.com/Metaswitch/clearwater-infrastructure/pull/369 went in, poll-cassandra started trying to connect to ::1 not 127.0.0.1. Cassandra was listening on 0.0.0.0, so anything trying to reach ::1 couldn't connect.
It looks like just binding to the IPv6 ANY address, ::, works. I've tested by applying this config and running:
```
/usr/share/clearwater/bin/poll-tcp 9160 127.0.0.1; echo $?
/usr/share/clearwater/bin/poll-tcp 9160 ::1; echo $?
/usr/share/clearwater/bin/poll-tcp 9160 localhost; echo $?
/usr/share/clearwater/bin/poll-tcp 9160 …
```
> [Reviewer: Richard] Listen on IPv6 ANY address

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
Nodetool commands should be run in the signalling namespace
> [Reviewer: Seb] Run nodetool commands in the signalling namespace

- clearwater-cassandra/usr/share/clearwater/cassandra_schema_utils.sh
Set the replication strategy as NetworkTopology if we're in a GR deployment. This used to be a manual step that was done for GR deployments, but we removed this step when we added the script below. However, the script used the wrong config option to determine if we're in a GR deployment.
> [Reviewer: Matt] Setup GR strategy

- clearwater-cassandra/etc/init.d/cassandra.clearwater
- clearwater-cassandra/usr/share/clearwater/bin/poll_cqlsh.sh
- clearwater-cassandra/usr/share/clearwater/conf/clearwater-cassandra.monit
This adds a stronger check that Cassandra is running (e.g. can we connect to cqlsh) that runs rarely. It also doesn't go through the init.d script to stop Cassandra (as this depends on the yaml file being present). This fixes issue #118 
Tested live
> [Reviewer: Seb] Add more cassandra checks

- clearwater-cassandra/etc/init.d/cassandra.clearwater
Should fix https://github.com/Metaswitch/clearwater-cassandra/issues/126
Tested live, by modifying the value in the pidfile, running `/etc/init.d/cassandra start`, and checking that it catches and logs the 'leaked' process, and starts a new one with a pid matching the new pidfile
> [reviewer: Ellie] Add sanity check to cassandra init file, to catch leaked processees

- debian/clearwater-cassandra.postrm
As described, this should clear out the state flags the cassandra-plugin will now put in place. 
This means that in the case of full removal and reinstall of cassandra, we should begin the clustering cycle fresh, even if we did not properly decommission before.
Testing live to see it works now.
> [No reveiewer] Add a postrm to remove plugin state files on remove and purge

- clearwater-cassandra/usr/share/clearwater/bin/poll_cassandra.sh
Cassandra now listens on all ports, and cassandra_hostname doesn't necessarily
refer to this cassandra. As such, we may end up believing Cassandra is alive because another Cassandra process is running on a different node.
This reverts the change made previously in https://github.com/Metaswitch/clearwater-issues/issues/761 - but I think this is the right think to do.
Current AIO nodes listen on 9160 on all interfaces:
```
[cw-aio]ubuntu@ec2-54-85-194-74:~$ sudo netstat -tnalp | grep java
...
tcp6       0      0 :::9160                 :::*                    LISTEN      2690/java
tcp6       0      0 127.0.0.1:9160          127.0.0.1:34028         ESTABLISHED 2690/java
...
```
> [Reviewer: Seb] Poll Cassandra on the local IP

- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra_schemas/run_cassandra_schemas
This makes the adding schemas command exit with a non-zero return code if any schema add fails.
> [Reviewer: Krista] Get return code from cassandra schemas

- clearwater-cassandra/usr/share/clearwater/cassandra_enabled
- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra.monit
- clearwater-cassandra/usr/share/clearwater/infrastructure/scripts/cassandra_cluster_manager
- debian/clearwater-cassandra.install
I've reviewed your part of these changes, and then made some further changes of my own. Can you take a look at the new changes here. It's basically:
* pull out the check for whether cassandra is required
* use that to install the cluster manager plugins if required
> [WIP] Disable Cassandra if not using it

- clearwater-cassandra/usr/share/clearwater/bin/restore_backup.sh
We don't want cassandra to restart between restoring different keyspaces on the
same node, nor do we want it to restart between restoring different nodes
So we need to move the stopping and starting of Cassandra out of the backup
script
Corresponding readthedocs changes here: https://github.com/Metaswitch/clearwater-readthedocs/pull/295
> [Reviewer: Adam] Don't stop and start Cassandra as part of restoring a backup

- clearwater-cassandra/etc/init.d/cassandra.clearwater
Hi Ellie, 
Could you please review this fix? SL has already reviewed this, however there was one concern he had (see bellow). 
This MR fixes an Issue with Cassandra startup - Cassandra starts when it shouldn't. The affected script checks for existence of certain files and is supposed to exit accordingly. The 'exit' command is however enclosed in parenthesis which starts a new subshell and consequently does not exit the main script.
I have tested the fix on our L3 homestead-prov deployment by temporarily removing the relevant files and checking that the script exits.
Possible concern (pointed out by SL):
Are we sure we want to exit at this point if the relevant files are missing - perhaps Cassandra is supposed to dynamically start working when those files appear, and by making it fail to …
> Fixed Cassandra startup
